name: llm-agent-chem
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - rdkit
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - tqdm
  - pip
  - pip:
      - openai
      - joblib
      - Flask==2.3.3
